---
task_name: AudioSepLoraTunedEmbeddingsMusdb18

data:
    train_datafiles:
        - 'datafiles/musdb18.train.json'
    validation_datafiles:
        - 'datafiles/musdb18.val.json'

    sampling_rate: 32000
    segment_seconds: 1
    loudness_norm:
        lower_db: -10
        higher_db: 10
    max_mix_num: 3
    with_mixture: True

train:
    precision: 32
    checkpoint_filename_args: 'optuna'
    logs_per_class: True
    lora_params:
        lora_dropout: 0.05
        lora_alpha: 16
        r: 8
    optimizer:
        optimizer_type: AdamW
        learning_rate: 1e-3
        warm_up_steps: 1
        reduce_lr_steps: 180
        lr_lambda_type: linear_warm_up
    num_nodes: 1
    num_workers: 8
    loss_type: l1_wav
    sync_batchnorm: True
    batch_size_per_device: 16
    steps_per_epoch: 18
    check_val_every_n_epoch: 1
    save_epoch_frequency: 10
    early_stop_steps: 1000001
    random_seed: 1234
    log_every_n_steps: 37
    segment_mixer_type: 'balanced'