---
task_name: AudioSepBaseMusdb18

data:
    train_datafiles:
        - 'datafiles/musdb18.train.json'
    validation_datafiles:
        - 'datafiles/musdb18.val.json'

    sampling_rate: 32000
    segment_seconds: 5
    loudness_norm:
        lower_db: -10
        higher_db: 10
    max_mix_num:  4
    with_mixture: True

train:
    precision: 32
    checkpoint_filename_args: 'base'
    logs_per_class: True
    optimizer:
        optimizer_type: AdamW
        learning_rate: 1e-3
        warm_up_steps: 100
        reduce_lr_steps: 500
        lr_lambda_type: linear_warm_up
    num_nodes: 1
    num_workers: 6
    loss_type: si_sdr
    sync_batchnorm: False
    batch_size_per_device: 16
    steps_per_epoch: 1000
    check_val_every_n_epoch: 1
    save_epoch_frequency: 10
    early_stop_steps: 1000001
    random_seed: 1234
    log_every_n_steps: 37
    segment_mixer_type: 'balanced'